<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE disco SYSTEM "disco.dtd">
<!-- 
<!DOCTYPE disco [
    <!ELEMENT disco (cancion+)>
        <!ELEMENT cancion (titulo, compositores, productores, sello, interprete)>
        <!ATTLIST cancion duracion CDATA #REQUIRED>
        <!ATTLIST cancion anio CDATA #REQUIRED>
            <!ELEMENT titulo (#PCDATA)>
            <!ELEMENT compositores (compositor+)>
                <!ELEMENT compositor (nombre, apellidos)>
                    <!ELEMENT nombre (#PCDATA)>
                    <!ELEMENT apellidos (#PCDATA)>
            <!ELEMENT productores (productor+)>
                <!ELEMENT productor (nombre, apellido)>
                    <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT sello (#PCDATA)>
            <!ELEMENT interprete (#PCDATA)>
]>
-->

<disco>
    <cancion duracion="" anio="">
        <titulo></titulo>
        <compositores>
            <compositor>
                <nombre></nombre>
                <apellidos></apellidos>
            </compositor>
        </compositores>
        <productores>
            <productor>
                <nombre></nombre>
                <apellido></apellido>
            </productor>
        </productores>
        <sello></sello>
        <interprete></interprete>
    </cancion>
    
</disco>
