=== cintiadiaz/moduloxml/20092019/email_carta XSD/mensajes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="mensajes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="mensaje" type="tipoMensaje" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="tipoMensaje">
    <xs:choice>
      <xs:element name="email" type="tipoEmail"/>
      <xs:element name="carta" type="tipoCarta"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="tipoEmail">
    <xs:sequence>
      <xs:element name="cabecera" type="tipoCabecera"/>
      <xs:element name="asunto" type="xs:string" minOccurs="0"/>
      <xs:element name="texto" type="tipoTexto" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="respuesta" default="no">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="si|no"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="tipoCabecera">
    <xs:sequence>
      <xs:element name="emisor" type="xs:string"/>
      <xs:element name="receptor" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="fecha" type="xs:date" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoCarta">
    <xs:sequence>
      <xs:element name="encabezado" type="tipoEncabezado"/>
      <xs:element name="texto" type="tipoTexto" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="respuesta" default="no">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="si|no"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="tipoEncabezado">
    <xs:sequence>
      <xs:element name="emisor" type="xs:string"/>
      <xs:element name="receptor" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="fecha" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoTexto" mixed="true">
    <xs:sequence minOccurs="0">
      <xs:element name="saludo" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== cintiadiaz/moduloxml/20092019/email_carta XSD/mensajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mensajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mensajes.xsd">
  <mensaje>
    <email respuesta="no">
      <cabecera>
        <emisor>antonio</emisor>
        <receptor>belen</receptor>
        <receptor>carlos</receptor>
      </cabecera>
      <asunto>Hola ¿Qué tal?</asunto>
      <texto>¿Queréis quedar otro día?
        <saludo>Hasta luego</saludo>
      </texto>
      <texto>pd: hace mucho calor</texto>
    </email>
  </mensaje>
  <mensaje>
    <carta respuesta="si">
      <encabezado>
        <emisor>elena</emisor>
        <receptor>esteban</receptor>
        <fecha>2019-09-20</fecha>
      </encabezado>
      <texto>Yo propongo ir a hacer la ruta del saja<saludo>Un saludo</saludo>ya me dices</texto>   
    </carta>
  </mensaje>
</mensajes>
