=== cintiadiaz/moduloxml/20082019/banco.dtd
<!ELEMENT sucursal (cuenta+)>
    <!ATTLIST sucursal codigo NMTOKEN #REQUIRED>
        <!ELEMENT cuenta (cliente, domiciliacion,prestamo)+>
            <!ATTLIST cuenta codigo NMTOKEN #REQUIRED>
                <!ELEMENT cliente (operacion+,privilegio)>
                    <!ATTLIST cliente NIF NMTOKEN #REQUIRED>
                        <!ELEMENT operacion (nombre, fecha)>
                            <!ELEMENT nombre (#PCDATA)>
                            <!ELEMENT fecha (#PCDATA)>
                        <!ELEMENT privilegio (#PCDATA)>
                <!ELEMENT domiciliacion (id,fecha,cantidad,concepto)>
                    <!ELEMENT id (#PCDATA)>
                    <!ELEMENT cantidad (#PCDATA)>
                    <!ELEMENT concepto (#PCDATA)>
                <!ELEMENT prestamo (id,fecha,cantidad,interes)>
                    <!ELEMENT interes (#PCDATA)>

=== cintiadiaz/moduloxml/20082019/banco_tansander.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sucursal SYSTEM "banco.dtd">
<sucursal codigo="123">
    <cuenta codigo="a123">
        <cliente NIF="72045">
            <operacion>
                <nombre></nombre>
                <fecha></fecha>
            </operacion>
            <privilegio></privilegio>
        </cliente>
        <domiciliacion>
            <id></id>
            <fecha></fecha>
            <cantidad></cantidad>
            <concepto></concepto>
        </domiciliacion>
        <prestamo>
            <id></id>
            <fecha></fecha>
            <cantidad></cantidad>
            <interes></interes>
        </prestamo>
    </cuenta>
</sucursal>
