<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas [
    <!ELEMENT facturas (factura+)>
        <!ELEMENT factura (emisor, cliente, detalle)>
            <!ATTLIST factura numero CDATA #REQUIRED>
            <!ATTLIST factura fecha CDATA #REQUIRED>
                <!ELEMENT emisor (nombre, CIF, telefono)>
                    <!ELEMENT nombre (#PCDATA)>
                    <!ELEMENT CIF (#PCDATA)>
                    <!ELEMENT telefono (#PCDATA)>
                <!ELEMENT cliente (nombre,CIF, telefono)>
                <!ELEMENT detalle (linea+)>
                    <!ATTLIST detalle importe CDATA #REQUIRED>
                        <!ELEMENT linea (descripcion, cantidad, oferta?, PVP)>
                            <!ATTLIST linea codigo-articulo ID #REQUIRED>
                            <!ATTLIST linea tipo (Libro|DVD|Varios) #IMPLIED>
                                <!ELEMENT descripcion (#PCDATA)>
                                <!ELEMENT cantidad (#PCDATA)>
                                <!ELEMENT oferta EMPTY>
                                <!ELEMENT PVP (#PCDATA)>

]>

<facturas>
    <factura numero="27" fecha="18/12/2013">
        <emisor>
            <nombre>Librería Pérez</nombre>
            <CIF>44555666B</CIF>
            <telefono>777888999</telefono>
        </emisor>
        <cliente>
            <nombre>Biblioteca Txantrea</nombre>
            <CIF>33111222A</CIF>
            <telefono>333999444</telefono>
        </cliente>
        <detalle importe="85€">
            <linea codigo-articulo="AW7" tipo="Libro">
                <descripcion>Analítica Web 2.0</descripcion>
                <cantidad>1</cantidad>
                <oferta/>
                <PVP>25€</PVP>
            </linea>
            <linea codigo-articulo="CP5" tipo="DVD">
                <descripcion>Curso de HTML</descripcion>
                <cantidad>2</cantidad>
                <PVP>30€</PVP>
            </linea>
        </detalle>
    </factura>
</facturas>