=== cintiadiaz/moduloxml/19092019/futbol DTD/futbol.dtd
<!ELEMENT temporada (jornada+)>
  <!ATTLIST temporada anyo CDATA #REQUIRED>
  <!ELEMENT jornada (partido+)>
    <!ATTLIST jornada numero CDATA #REQUIRED>
      <!ELEMENT partido (fecha, estadio, local, visitante,resultado?, aplazado?)>
        <!ATTLIST partido numero CDATA #REQUIRED>
          <!ELEMENT fecha (#PCDATA)>
          <!ELEMENT estadio (#PCDATA)>
            <!ATTLIST estadio asistencia CDATA #IMPLIED>
          <!ELEMENT local (#PCDATA)>
          <!ELEMENT visitante (#PCDATA)>
          <!ELEMENT resultado EMPTY>
            <!ATTLIST resultado local CDATA #REQUIRED
                                                  visitante CDATA #REQUIRED>
           <!ELEMENT aplazado EMPTY>

=== cintiadiaz/moduloxml/19092019/futbol DTD/futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada SYSTEM "futbol.dtd">
<temporada anyo="2007">
  <jornada numero="1">
    <partido numero="1">
      <fecha>2007-09-04</fecha>
      <estadio asistencia="53000">Vicente Calderon</estadio>
      <local>At. Madrid</local>
      <visitante>Sevilla</visitante>
      <resultado local="3" visitante="1" />
    </partido>
    <partido numero="2">
      <fecha>2007-09-05</fecha>
      <estadio asistencia="26000">La Rosaleda</estadio>
      <local>Málaga</local>
      <visitante>Zaragoza</visitante>
      <resultado local="0" visitante="2" />
    </partido>
 </jornada>
  <jornada numero="2">
    <partido numero="1">
      <fecha>2007-09-11</fecha>
      <estadio>Santiago Bernabeu</estadio>
      <local>R. Madrid</local>
      <visitante>Dep. Corunya</visitante>
      <aplazado/>
  </jornada>
</temporada>
